#########################
## Sample Sass Lint File
#########################
# Rule Configuration
rules:
  class-name-format:
    - 2
    -
      convention: ^[\-A-Za-z0-9]+$
  variable-name-format:
    - 0
  mixin-name-format:
    - 0